# docker-compose.db.yml
services:
  pg:
    image: postgres:15
    container_name: chitta_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bakultahu.566
      POSTGRES_DB: Db_stressapp
    ports:
      - "5433:5432"         # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: chitta_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"

volumes:
  pgdata:
